# Site settings
title: K3PO
email: organization-site@kaazing.com
description: "K3PO"
baseurl: ""
url: https://k3po.github.io
highlighter: pygments

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
categories: [general]
relative_permalinks: false

redcarpet:
  extensions: ["fenced_code_blocks"]
  input: "GFM"

gems:
#  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
#  - jekyll-sitemap
